spring.application.name=demo
server.port=${PORT}

# PostgreSQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP 설정 추가 (연결 풀 최적화)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret Key 설정 (환경 변수로 변경)
jwt.secret=${JWT_SECRET}

# Spring Boot Actuator 활성화
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# 현재 설정된 포트 로그로 출력
logging.level.org.springframework.web=DEBUG
