spring.application.name=demo
server.port=8081

spring.datasource.url=jdbc:postgresql://dpg-cv5afnt6l47c73d2hh4g-a.oregon-postgres.render.com:5432/mydb_33vw
spring.datasource.username=myuser
spring.datasource.password=c0FSMlXmxyOZMbaezP4P0tsKUYa3OcnI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret Key 설정
# JWT Secret Key 설정
jwt.secret=EdooXuhSMM8gkpUjAdbGwIS6S4aw4wMkj62EcRaL458=

